format_version = "1.0"

texts = {
    -- GLOBAL
    ["text_OnOff"] = "Device On",
    ["text_Off"] = "Off",
    ["text_On"] = "On",

    -- VOICES
    ["text_Voice"] = "Primary Voice",
    ["text_AlterEgo"] = "Alter Ego Voice",
    ["text_voice_0"] = "Voice 1",
    ["text_voice_1"] = "Voice 2",
    ["text_voice_2"] = "Voice 3",
    ["text_voice_3"] = "Voice 4",
    ["text_voice_4"] = "Voice 5",
    ["text_voice_5"] = "Voice 6",
    ["text_voice_6"] = "Voice 7",
    ["text_voice_7"] = "Voice 8",

    -- STATE CONTROLS
    ["text_Feedback"] = "Feedback",
    ["text_Freeze"] = "Freeze",

    -- PITCH & SCALE
    ["text_KeyLock"] = "Key Lock",
    ["text_ScaleRoot"] = "Scale Root",
    ["text_root_0"] = "C",
    ["text_root_1"] = "C#",
    ["text_root_2"] = "D",
    ["text_root_3"] = "D#",
    ["text_root_4"] = "E",
    ["text_root_5"] = "F",
    ["text_root_6"] = "F#",
    ["text_root_7"] = "G",
    ["text_root_8"] = "G#",
    ["text_root_9"] = "A",
    ["text_root_10"] = "A#",
    ["text_root_11"] = "B",
    ["text_root_12"] = "Free",
    ["text_root_13"] = "Auto",
    
    ["text_ScaleMode"] = "Scale Mode",
    ["text_mode_0"] = "Major",
    ["text_mode_1"] = "Minor",
    ["text_mode_2"] = "Harmonic Minor",
    ["text_mode_3"] = "Melodic Minor",
    ["text_mode_4"] = "Dorian",
    ["text_mode_5"] = "Phrygian",
    ["text_mode_6"] = "Lydian",
    ["text_mode_7"] = "Mixolydian",
    ["text_mode_8"] = "Chromatic",
    
    ["text_Mutation"] = "Mutation",
    ["text_Octave"] = "Octave",
    ["text_oct_m3"] = "-3 Oct",
    ["text_oct_m2"] = "-2 Oct",
    ["text_oct_m1"] = "-1 Oct",
    ["text_oct_0"] = "0",
    ["text_oct_p1"] = "+1 Oct",
    ["text_oct_p2"] = "+2 Oct",
    ["text_oct_p3"] = "+3 Oct",

    -- RHYTHM & DYNAMICS
    ["text_Rate"] = "Rate",
    ["text_rate_0"] = "Off (Free)",
    ["text_rate_1"] = "4 Bars",
    ["text_rate_2"] = "2 Bars",
    ["text_rate_3"] = "1 Bar",
    ["text_rate_4"] = "1/2",
    ["text_rate_5"] = "1/2D",
    ["text_rate_6"] = "1/2T",
    ["text_rate_7"] = "1/4",
    ["text_rate_8"] = "1/4D",
    ["text_rate_9"] = "1/4T",
    ["text_rate_10"] = "1/8",
    ["text_rate_11"] = "1/8D",
    ["text_rate_12"] = "1/8T",
    ["text_rate_13"] = "1/16",
    ["text_rate_14"] = "1/16D",
    ["text_rate_15"] = "1/16T",
    ["text_rate_16"] = "1/32",
    ["text_rate_17"] = "1/32D",
    ["text_rate_18"] = "1/32T",
    ["text_rate_19"] = "1/64",
    
    ["text_Density"] = "Density",
    ["text_Length"] = "Length",
    ["text_Swing"] = "Swing",
    ["text_Velocity"] = "Velocity",
    ["text_Accent"] = "Accent",

    -- THE ENGINE (Generative Controls)
    ["text_ResponseMode"] = "Response Mode",
    ["text_resp_mirror"] = "Mirror",
    ["text_resp_upsidedown"] = "Upside Down",
    ["text_resp_warp"] = "Warp",
    ["text_resp_retro"] = "Retrograde",
    ["text_resp_shuffle"] = "Shuffle",
    ["text_resp_pendulum"] = "Pendulum",
    ["text_resp_cascadeup"] = "Cascade Up",
    ["text_resp_cascadedown"] = "Cascade Down",
    ["text_resp_chord"] = "Chord",

    ["text_ResponseLength"] = "Phrase Stretch",
    ["text_len_025"] = "1/4x",
    ["text_len_05"] = "1/2x",
    ["text_len_1"] = "1x",
    ["text_len_15"] = "1.5x",
    ["text_len_2"] = "2x",
    ["text_len_25"] = "2.5x",
    ["text_len_3"] = "3x",
    ["text_len_4"] = "4x",

    ["text_Drift"] = "Drift",
    ["text_Harmony"] = "Harmony",

    ["text_Choke"] = "Playback Mode",
    ["text_Duet"] = "Duet",
    ["text_ChokeMode"] = "Answer",

    ["text_Seed"] = "Seed",
    ["text_Clear"] = "Clear",
    ["text_Sync"] = "Tempo Sync",
    ["text_Free"] = "Free",
    
    ["text_SilenceThreshold"] = "Silence Threshold",
    ["text_Patience"] = "Patience",
    ["text_Memory"] = "Memory",
    
    ["text_sync_off"] = "Off",
    ["text_sync_1_64"] = "1/64",
    ["text_sync_1_32"] = "1/32",
    ["text_sync_1_16"] = "1/16",
    ["text_sync_1_8"] = "1/8",
    ["text_sync_1_4"] = "1/4",
    ["text_sync_1_2"] = "1/2",
    ["text_sync_1_bar"] = "1 Bar",
    ["text_sync_2_bar"] = "2 Bars",
    ["text_sync_4_bar"] = "4 Bars",
    
    ["text_Loop"] = "Loop Count",
    ["text_loop_1"] = "1x",
    ["text_loop_2"] = "2x",
    ["text_loop_3"] = "3x",
    ["text_loop_4"] = "4x",
    ["text_loop_8"] = "8x",
    ["text_loop_16"] = "16x",
    ["text_loop_32"] = "32x",
    ["text_loop_inf"] = "Infinite",
    
    ["text_KeepInput"] = "Keep Input",
    ["text_Transpose"] = "Transpose",

    -- CONTROL SECTION
    ["text_LowLimit"] = "Low Limit",
    ["text_HighLimit"] = "High Limit",
    ["text_Direction"] = "Direction",
    ["text_dir_bounce"] = "Bounce",
    ["text_dir_reset"] = "Reset",

    -- MIDI NOTE NAMES (MIDI 0=C-2 through 127=G8)
    ["text_note_0"] = "C-2",
    ["text_note_1"] = "C#-2",
    ["text_note_2"] = "D-2",
    ["text_note_3"] = "D#-2",
    ["text_note_4"] = "E-2",
    ["text_note_5"] = "F-2",
    ["text_note_6"] = "F#-2",
    ["text_note_7"] = "G-2",
    ["text_note_8"] = "G#-2",
    ["text_note_9"] = "A-2",
    ["text_note_10"] = "A#-2",
    ["text_note_11"] = "B-2",
    ["text_note_12"] = "C-1",
    ["text_note_13"] = "C#-1",
    ["text_note_14"] = "D-1",
    ["text_note_15"] = "D#-1",
    ["text_note_16"] = "E-1",
    ["text_note_17"] = "F-1",
    ["text_note_18"] = "F#-1",
    ["text_note_19"] = "G-1",
    ["text_note_20"] = "G#-1",
    ["text_note_21"] = "A-1",
    ["text_note_22"] = "A#-1",
    ["text_note_23"] = "B-1",
    ["text_note_24"] = "C0",
    ["text_note_25"] = "C#0",
    ["text_note_26"] = "D0",
    ["text_note_27"] = "D#0",
    ["text_note_28"] = "E0",
    ["text_note_29"] = "F0",
    ["text_note_30"] = "F#0",
    ["text_note_31"] = "G0",
    ["text_note_32"] = "G#0",
    ["text_note_33"] = "A0",
    ["text_note_34"] = "A#0",
    ["text_note_35"] = "B0",
    ["text_note_36"] = "C1",
    ["text_note_37"] = "C#1",
    ["text_note_38"] = "D1",
    ["text_note_39"] = "D#1",
    ["text_note_40"] = "E1",
    ["text_note_41"] = "F1",
    ["text_note_42"] = "F#1",
    ["text_note_43"] = "G1",
    ["text_note_44"] = "G#1",
    ["text_note_45"] = "A1",
    ["text_note_46"] = "A#1",
    ["text_note_47"] = "B1",
    ["text_note_48"] = "C2",
    ["text_note_49"] = "C#2",
    ["text_note_50"] = "D2",
    ["text_note_51"] = "D#2",
    ["text_note_52"] = "E2",
    ["text_note_53"] = "F2",
    ["text_note_54"] = "F#2",
    ["text_note_55"] = "G2",
    ["text_note_56"] = "G#2",
    ["text_note_57"] = "A2",
    ["text_note_58"] = "A#2",
    ["text_note_59"] = "B2",
    ["text_note_60"] = "C3",
    ["text_note_61"] = "C#3",
    ["text_note_62"] = "D3",
    ["text_note_63"] = "D#3",
    ["text_note_64"] = "E3",
    ["text_note_65"] = "F3",
    ["text_note_66"] = "F#3",
    ["text_note_67"] = "G3",
    ["text_note_68"] = "G#3",
    ["text_note_69"] = "A3",
    ["text_note_70"] = "A#3",
    ["text_note_71"] = "B3",
    ["text_note_72"] = "C4",
    ["text_note_73"] = "C#4",
    ["text_note_74"] = "D4",
    ["text_note_75"] = "D#4",
    ["text_note_76"] = "E4",
    ["text_note_77"] = "F4",
    ["text_note_78"] = "F#4",
    ["text_note_79"] = "G4",
    ["text_note_80"] = "G#4",
    ["text_note_81"] = "A4",
    ["text_note_82"] = "A#4",
    ["text_note_83"] = "B4",
    ["text_note_84"] = "C5",
    ["text_note_85"] = "C#5",
    ["text_note_86"] = "D5",
    ["text_note_87"] = "D#5",
    ["text_note_88"] = "E5",
    ["text_note_89"] = "F5",
    ["text_note_90"] = "F#5",
    ["text_note_91"] = "G5",
    ["text_note_92"] = "G#5",
    ["text_note_93"] = "A5",
    ["text_note_94"] = "A#5",
    ["text_note_95"] = "B5",
    ["text_note_96"] = "C6",
    ["text_note_97"] = "C#6",
    ["text_note_98"] = "D6",
    ["text_note_99"] = "D#6",
    ["text_note_100"] = "E6",
    ["text_note_101"] = "F6",
    ["text_note_102"] = "F#6",
    ["text_note_103"] = "G6",
    ["text_note_104"] = "G#6",
    ["text_note_105"] = "A6",
    ["text_note_106"] = "A#6",
    ["text_note_107"] = "B6",
    ["text_note_108"] = "C7",
    ["text_note_109"] = "C#7",
    ["text_note_110"] = "D7",
    ["text_note_111"] = "D#7",
    ["text_note_112"] = "E7",
    ["text_note_113"] = "F7",
    ["text_note_114"] = "F#7",
    ["text_note_115"] = "G7",
    ["text_note_116"] = "G#7",
    ["text_note_117"] = "A7",
    ["text_note_118"] = "A#7",
    ["text_note_119"] = "B7",
    ["text_note_120"] = "C8",
    ["text_note_121"] = "C#8",
    ["text_note_122"] = "D8",
    ["text_note_123"] = "D#8",
    ["text_note_124"] = "E8",
    ["text_note_125"] = "F8",
    ["text_note_126"] = "F#8",
    ["text_note_127"] = "G8",

    -- CV JACKS
    ["text_FeedbackCV"] = "Feedback CV",
    ["text_FreezeCV"] = "Freeze CV",
    ["text_RateCV"] = "Rate CV",
    ["text_DensityCV"] = "Density CV",
    ["text_LengthCV"] = "Length CV",
    ["text_SwingCV"] = "Swing CV",
    ["text_VelocityCV"] = "Velocity CV",
    ["text_AccentCV"] = "Accent CV",
    ["text_MutationCV"] = "Mutation CV",
    ["text_OctaveCV"] = "Octave CV",
    ["text_ResponseCV"] = "Response Mode CV",
    ["text_ChokeCV"] = "Choke CV",
    ["text_SeedCV"] = "Seed CV",
    ["text_SilenceThresholdCV"] = "Silence Threshold CV",
    ["text_PatienceCV"] = "Patience CV",
    ["text_MemoryCV"] = "Memory CV",
    ["text_LoopCV"] = "Loop CV",
    ["text_TransposeCV"] = "Transpose CV",
    
    ["text_CVNote_Main"] = "Note Out (Main)",
    ["text_CVGate_Main"] = "Gate Out (Main)",
    ["text_CVNote_AlterEgo"] = "Note Out (Alter Ego)",
    ["text_CVGate_AlterEgo"] = "Gate Out (Alter Ego)",

    -- CV TRIMS
    ["text_Trim_Feedback"] = "Feedback Trim",
    ["text_Trim_Freeze"] = "Freeze Trim",
    ["text_Trim_Rate"] = "Rate Trim",
    ["text_Trim_Density"] = "Density Trim",
    ["text_Trim_Length"] = "Length Trim",
    ["text_Trim_Swing"] = "Swing Trim",
    ["text_Trim_Velocity"] = "Velocity Trim",
    ["text_Trim_Accent"] = "Accent Trim",
    ["text_Trim_Mutation"] = "Mutation Trim",
    ["text_Trim_Octave"] = "Octave Trim",
    ["text_Trim_Response"] = "Response Trim",
    ["text_Trim_Choke"] = "Choke Trim",
    ["text_Trim_Seed"] = "Seed Trim",
    ["text_Trim_SilenceThreshold"] = "Silence Threshold Trim",
    ["text_Trim_Patience"] = "Patience Trim",
    ["text_Trim_Memory"] = "Memory Trim",
    ["text_Trim_Loop"] = "Loop Trim",
    ["text_Trim_Transpose"] = "Transpose Trim",

    -- UI GROUPS
    ["text_GroupState"] = "State",
    ["text_GroupPitch"] = "Pitch",
    ["text_GroupVoices"] = "Voices",
    ["text_GroupRhythm"] = "Rhythm",
    ["text_GroupEngine"] = "Engine",

    -- REMOTE SHORT NAMES
    ["text_short_OnOff"] = "OnOff", ["text_shortest_OnOff"] = "On",
    ["text_short_Feedback"] = "Fdbk", ["text_shortest_Feedback"] = "Fbk",
    ["text_short_Freeze"] = "Freeze", ["text_shortest_Freeze"] = "Frz",
    ["text_short_KeyLock"] = "KeyLck", ["text_shortest_KeyLock"] = "Klk",
    ["text_short_ScaleRoot"] = "Root", ["text_shortest_ScaleRoot"] = "Rt",
    ["text_short_ScaleMode"] = "Scale", ["text_shortest_ScaleMode"] = "Scl",
    ["text_short_Voice"] = "Voice", ["text_shortest_Voice"] = "Voc",
    ["text_short_AlterEgo"] = "AltEgo", ["text_shortest_AlterEgo"] = "Alt",
    ["text_short_Rate"] = "Rate", ["text_shortest_Rate"] = "Rt",
    ["text_short_Density"] = "Dens", ["text_shortest_Density"] = "Den",
    ["text_short_Length"] = "Len", ["text_shortest_Length"] = "Ln",
    ["text_short_Swing"] = "Swing", ["text_shortest_Swing"] = "Swg",
    ["text_short_Velocity"] = "Veloc", ["text_shortest_Velocity"] = "Vel",
    ["text_short_Accent"] = "Accent", ["text_shortest_Accent"] = "Acc",
    ["text_short_Mutation"] = "Mutate", ["text_shortest_Mutation"] = "Mut",
    ["text_short_Octave"] = "Octave", ["text_shortest_Octave"] = "Oct",
    ["text_short_ResponseMode"] = "Resp", ["text_shortest_ResponseMode"] = "Rsp",
    ["text_short_ResponseLen"] = "Length", ["text_shortest_ResponseLen"] = "Len",
    ["text_short_Drift"] = "Drift", ["text_shortest_Drift"] = "Drf",
    ["text_short_Harmony"] = "Harm", ["text_shortest_Harmony"] = "Hrm",
    ["text_short_Choke"] = "Choke", ["text_shortest_Choke"] = "Chk",
    ["text_short_Seed"] = "Seed", ["text_shortest_Seed"] = "Sd",
    ["text_short_Sync"] = "Sync", ["text_shortest_Sync"] = "Snc",
    ["text_short_SilenceThreshold"] = "Silnce", ["text_shortest_SilenceThreshold"] = "Sil",
    ["text_short_Patience"] = "Patnce", ["text_shortest_Patience"] = "Pat",
    ["text_short_Memory"] = "Memory", ["text_shortest_Memory"] = "Mem",
    ["text_short_Loop"] = "Loop", ["text_shortest_Loop"] = "Lp",
    ["text_short_KeepInput"] = "KeepIn", ["text_shortest_KeepInput"] = "KIn",
    ["text_short_Transpose"] = "Transp", ["text_shortest_Transpose"] = "Trn",
    ["text_short_Clear"] = "Clear",  ["text_shortest_Clear"] = "Clr",
    ["text_short_LowLimit"] = "LoLim", ["text_shortest_LowLimit"] = "Lo",
    ["text_short_HighLimit"] = "HiLim", ["text_shortest_HighLimit"] = "Hi",
    ["text_short_Direction"] = "Dir",   ["text_shortest_Direction"] = "Dir",

    ["text_HarmonyCV"] = "Harmony CV",
    ["text_ClearCV"] = "Clear CV",
    ["text_LowLimitCV"] = "Low Limit CV",
    ["text_HighLimitCV"] = "High Limit CV",
    ["text_DirectionCV"] = "Direction CV",

    ["text_Trim_Harmony"] = "Harmony Trim",
    ["text_Trim_Clear"] = "Clear Trim",
    ["text_Trim_LowLimit"] = "Low Limit Trim",
    ["text_Trim_HighLimit"] = "High Limit Trim",
    ["text_Trim_Direction"] = "Direction Trim"
}
